### PR TITLE
Pin torch version until deprecated functionality is fixed

### PR DESCRIPTION
**Pull request by Hardcode84**
Recent torch 2.5 versions failing with `ImportError: cannot import name 'dynamic_dim' from 'torch.export'`, pin torch version `<2.5.0` for now, until proper fix is ready https://github.com/iree-org/iree-turbine/pull/145

### CODE REVIEW

**Comment by harsh-nod** [comment]
thanks! this will help keep the builders green till we figure out how to migrate to 2.6.

**Review by harsh-nod — APPROVED** [review]

**Comment by stellaraccident** [comment]
Can you please note what the issue was?

I'm working on this for 2.6 support: https://github.com/iree-org/iree-turbine/pull/145

**Comment by Hardcode84** [comment]
This is exactly because of missing `dynamic_dim` issue, see https://github.com/iree-org/iree-turbine/actions/runs/10876749148/job/30182209664 for example.

Also, pip reports it's still torch 2.5, not 2.6

**Comment by Hardcode84** [comment]
let me try, actually

**Comment by Hardcode84** [comment]
yep, <2.6 doesn't work

**Comment by stellaraccident** [comment]
> This is because of missing `dynamic_dim` issue, see https://github.com/iree-org/iree-turbine/actions/runs/10876749148/job/30182209664 for example.
> 
> Also, pip reports it's still torch 2.5, not 2.6

Update the PR description please and note that #145 is in progress to fix this.

**Review by stellaraccident — APPROVED** [review]
